/*
This has been generated by the overpass-turbo wizard.
The original search was:
“amenity=bicycle_parking”
*/
[out:csv(::"id", ::lat, ::lon, amenity, capacity)][timeout:25];
// gather results
(
  // query part for: “amenity=bicycle_parking”
  node["amenity"="bicycle_parking"]({{bbox}});
  way["amenity"="bicycle_parking"]({{bbox}});
  relation["amenity"="bicycle_parking"]({{bbox}});
);
// print results
out body;
>;
out skel qt;
